var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,c){if(d){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in b||(b[e]={});b=b[e]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Object.is",function(a){return a?a:function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,b){var c=this;c instanceof String&&(c=String(c));var d=c.length;b=b||0;for(0>b&&(b=Math.max(b+d,0));b<d;b++){var f=c[b];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");
$jscomp.checkStringArgs=function(a,d,b){if(null==a)throw new TypeError("The 'this' value for String.prototype."+b+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+b+" must not be a regular expression");return a+""};$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,b){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,b||0)}},"es6","es3");var mainLink=document.getElementById("main-link");
mainLink.style.display="none";var scrollLimit=550,scrollRange=100,intersected="#skils"===window.location.hash,barIntersected="#experience"===window.location.hash,options={root:document.querySelector("#scrollArea"),rootMargin:"0px",threshold:1};
window.addEventListener("DOMContentLoaded",function(){var a=function(){var a=document.body.querySelector("#mainNav");a&&(0===window.scrollY?a.classList.remove("navbar-shrink"):a.classList.add("navbar-shrink"))};a();document.addEventListener("scroll",a);document.body.querySelector("#mainNav")&&new bootstrap.ScrollSpy(document.body,{target:"#mainNav",offset:72});var d=document.body.querySelector(".navbar-toggler");[].slice.call(document.querySelectorAll("#navbarResponsive .nav-link")).map(function(a){a.addEventListener("click",
function(){"none"!==window.getComputedStyle(d).display&&d.click()})});a=new IntersectionObserver(animateSkilBars,options);var b=new IntersectionObserver(displayExperienceBar,options);a.observe(document.getElementById("skils"));b.observe(document.getElementById("expOdOs"));b.observe(document.getElementById("expOttobock"));b.observe(document.getElementById("expCSGermany"));b.observe(document.getElementById("expCSPorto"));b.observe(document.getElementById("expBitBrain"));b.observe(document.getElementById("expUminho"))});
var displayExperienceBar=function(a){barIntersected&&!a[0].target.className.includes("fadeIn")&&(a[0].target.className+=" fadeIn",a[0].target.style.opacity=1);1>=barIntersected&&barIntersected++},animateBar=function(a,d,b){var c=0,e=setInterval(function(){c>=d?clearInterval(e):(c++,a.style.width=c+"%",a.innerHTML=c+"%")},void 0===b?10:b)},animateSkilBars=function(){1==intersected&&(animateBar(document.getElementById("skilsTypeScript"),97),animateBar(document.getElementById("skilsCCpp"),95),animateBar(document.getElementById("skilsCsh"),
92),animateBar(document.getElementById("skilsDocker"),90),animateBar(document.getElementById("skilsPython"),93),animateBar(document.getElementById("skilsGit"),97),animateBar(document.getElementById("skilsGraphQl"),85),animateBar(document.getElementById("skilsAws"),80));1>=intersected&&intersected++},fade=function(a,d){(a.style.opacity=d)?a.style.removeProperty("display"):a.style.display="none"};
window.onscroll=function(){fade(mainLink,Math.min(Math.max((window.scrollY-scrollLimit+scrollRange)/(2*scrollRange),0),1))};
var submitContactForm=function(){var a=document.getElementById("contactForm");a.classList.add("was-validated");if(a.checkValidity()){a.classList.remove("was-validated");a=document.getElementById("name").value;var d=document.getElementById("email").value,b=document.getElementById("message").value;a={name:a,email:d,message:b};var c=new XMLHttpRequest;c.open("POST","https://ov6s2qc9d6.execute-api.eu-west-3.amazonaws.com/live",!0);c.setRequestHeader("Content-Type","application/json");c.onload=function(){if(200===
c.status){var a=document.getElementById("submitSuccessMessage"),b=document.getElementById("submitButton");a.classList.remove("d-none");b.classList.add("d-none")}else alert("Sorry, there was an error sending your message. Please try again later.")};c.send(JSON.stringify(a))}};